// Generated by CoffeeScript 1.6.3
steroids.config.name = "Frankie";

steroids.config.location = "http://localhost/views/frankie/index.html";

steroids.config.navigationBar.tintColor = "#273552";

steroids.config.navigationBar.titleColor = "#ffffff";

steroids.config.navigationBar.buttonTintColor = "#ff6b26";

steroids.config.navigationBar.buttonTitleColor = "#ff6b26";

steroids.config.loadingScreen.tintColor = "#262626";

steroids.config.statusBar.enabled = true;

steroids.config.statusBar.style = "light";

steroids.config.watch.exclude = ["www"];
